### ISSUE TITLE
roadtrip and mapsource map crash on the 20010328 map

### ISSUE THREAD

**Issue by maning** [maning/osmphgps#10]
Mapsource crash report below:

`
App: MapSource
At: 3/28/2011 3:55:30 AM (UTC)
OS: Windows XP Service Pack 3
Processor: Pentium Pro or Pentium II, RAM: 2047472
GEO_POSITION.HPP-62-6.11.6.0
Language ID: 1033
Part Number: 006-A0041-00
Build Type: Release
`

**Comment by maning** [comment]
The crash also happens with the macroadtrip/basecamp installer.  I tested an older file (< 400 MB) and everything works fine.  This could be either a corrupted extract or RAM problem.

**Comment by ralleon** [comment]
Same here. I download today's version release, it crashed on my mapsource.

**Comment by maning** [comment]
@ralleon, have you tried compiling yourself?  Please compile and report if you have similar issues.

**Comment by ralleon** [comment]
using my preferred mkgmap v1867, yesterday's philippine.osm.pbf compiled/ran
well on beta version (which showed edits in palawan & jalajala which i did
the other day)

i'm hesitant at the moment to use later versions of mkgmap because of the
missing-same-name-cities issue.

**Comment by maning** [comment]
@ralleon, ah you are using the pbf format?  Can you try the osm xml instead?  I'll try v1867 as well.

**Comment by maning** [comment]
test1 - using the latest extract dated 20110328
mkgmap r-1867 - macroadtrip incomplete mapbuild and winmapsource crash
mkgmap r-1905 - macroadtrip incomplete mapbuild and winmapsource crash

test2 - using an old extract 20110321
mkgmap r-1867 - both mapsource and roadtrip build OK
mkgmap r-1905 - both mapsource and roadtrip build OK

I conclude that there are issues with the current data.

**Comment by ralleon** [comment]
i used 0328 osm.pbf - compiled well with r1867. it may be the mkgmap
switches. maybe i'm still using a conservative switches that is more fault
tolerant. anyway, i also suspect there is something wrong with the data.
main suspect are polygons - hula ko lang :-)

**Comment by maning** [comment]
Tested using pbf format and the compile is complete.  Thanks @ralleon for the advice!
