### ISSUE TITLE
Mon Mar 28 20:17:43 PHT 2011 Mapsource Installer Crash

### ISSUE THREAD

**Issue by timexRiel** [maning/osmphgps#11]
Hi Maning, this my first post here. Let me know if I miss anything in this post.

-My Mapsource app crashes everytime i select your recent map. Reverted back to a previous installer and it doesn't have any problem.

Thanks.
-barspan

**Comment by maning** [comment]
@barspan,  thanks for reporting, we are looking at the issue now see similar report:
https://github.com/maning/osmphgps/issues/#issue/10

**Comment by timexRiel** [comment]
yeah, i noticed that the latest posts are actually at the bottom of the list after i created my first post. my bad. i apologize for the double post on the issue. will track that thread instead. thanks.
