### ISSUE TITLE
info on street thats one way

### ISSUE THREAD

**Issue by yongsama65** [maning/osmphgps#17]
hi. I'm a newbie so don't know much on how to contribute.  I just want to note that the street in between abad santos and p. guevara (v cruz) is one way going to p. guevara. Thats in San Juan.  Also, the small section of abad santos that is from lopes jaena to wilson is also one way (direction is only from wilson to lopes jaena).  Thanks.  Hope you can make the update on the next update.

**Comment by maning** [comment]
Fixed: http://www.openstreetmap.org/browse/changeset/8158640

Please verify and check.
