### ISSUE TITLE
address/street search not working on 4-digit Nuvi (i.e. 1200, 1310)

### ISSUE THREAD

**Issue by maning** [maning/osmphgps#19]
I tried the latest map update on the newer Garmin nuvi models, the address searching is not working. But it works fine on the older series of nuvi's.  On the new ones, when you click on the Address icon, it displays an error "No Map Data Available".  This was not the case on your update a couple of months ago. The address searching on the previous map update was working fine on both the new and older nuvi's.

**Comment by ralleon** [comment]
???? :-( di kaya ito yung binabanggit sa RG about the 4-digit nuvi's.

or is it my hack that's messing with newer Garmin. But without the hack, you
also know what will happen...

**Comment by maning** [comment]
Same behavior with Nuvi 1490t and 1310

**Comment by maning** [comment]
Compiled using the mkgmap-city-region-index-r1992.  @ralleon, please test.

**Comment by maning** [comment]
Seems to be fixed with the mkgmap-city-region-index-r1992.  Will wait for more reports before closing this issue.

**Comment by maning** [comment]
from dongsese:
nuvi 3790T - address search now works when transferred via mapsource. but not with direct gmapsupp transfer.
