### ISSUE TITLE
Selecting Makati shows 3 variations of Makati City but only one can search streets

### ISSUE THREAD

**Issue by maning** [maning/osmphgps#22]
Using Nuvi 255w.
1. `Where to` > `Address` > `Spell City`. 
2.  I spelled Makati, which has 3 variations of the City Name

Makati, Ncr
Makati City, PHL
Makati City
1. Selecting any of the Makati names goes to the `Enter Housenumber` and `Enter Street` which gives you a full list of streets in the city.  However, only the `Makati, Ncr` city can find a matching street for routing.

Some city/towns i. e. Marikina have only one option in the `Spell City`

**Comment by ralleon** [comment]
Under our current address hack, for any POI can only be searchable (with
city filter), the city-POI should have an is_in:state tag,
eg.
name=Makati
place=city
is_in:state=NCR

else the particular city-POI becomes a free-floating city... and all other
POI's will not associate to that particular city.

Find the other Makati City poi's and delete them. There should only be one
official city-poi.

All POI's in Makati with addr:city=Makati City should be converted to
addr:city=Makati to ensure no conflict

**Comment by maning** [comment]
I changed all "Makati City" to "Makati" in the addr:city and is_in:state tags.  Latest dev/beta map now showing only one Makati,NCR in the `Spell City` .
