### ISSUE TITLE
[Beta] Rule to force "ñ" on city names results in "?" instead

### ISSUE THREAD

**Issue by seav** [maning/osmphgps#25]
Rally's rule in the beta map to convert all "Paranaque", "Las Pinas" and "Dasmarinas" values for "addr:city" and "is_in:city" keys to have "ñ" instead of "n" results in "?" instead (such as "Para?aque").

I am not sure but I think that the text file containing the rules for mkgmap should always be saved in UTF-8 format to match the UTF-8 encoding of the OSM data. When editing the rule file in Windows Notepad, always select the Encoding=UTF-8 option in the save dialog box.

**Comment by maning** [comment]
@seav, are you looking at the code via github?  I noticed this as well, but I don't see it in my repo.

**Comment by ralleon** [comment]
In my mapsource & gps, no problem so far with . Where did you observe this?
Nuvi or your text editor?

I'm using Textpad5, should I enable "Write Unicode and UTF-8 BOM"?

**Comment by seav** [comment]
@maning, I observed this in the nuvi. But now that I looked at the
code online at github, I saw "?" in the code as well:

https://github.com/maning/osmphgps/blob/master/styles/default/points#L126

The github page is served in UTF-8 encoding so seeing "Para�e", "Las
Pi�" and "Dasmari�" on the web page itself means that the encoding of
the text file is wrong.

On Sat, Jun 25, 2011 at 6:04 AM, maning
reply@reply.github.com
wrote:

> @seav, are you looking at the code via github?  I noticed this as well, but I don't see it in my repo.

**Comment by seav** [comment]
@rally,

Can you try that? Hopefully it will work, but doing some research
showed me this:

"Another criticism is that, as of version 5.2.0, TextPad is not
Unicode compatible, even though it offers UTF-8 and UTF-16 as
encodings in which files can be loaded and saved."
http://forums.textpad.com/viewtopic.php?t=4777

Maybe use another editor? :-p

On Sat, Jun 25, 2011 at 7:33 AM, ralleon
reply@reply.github.com
wrote:

> In my mapsource & gps, no problem so far with . Where did you observe this?
> Nuvi or your text editor?
> 
> I'm using Textpad5, should I enable "Write Unicode and UTF-8 BOM"?
> 
> On Sat, Jun 25, 2011 at 12:00 AM, seav <

**Comment by maning** [comment]
@ralleon, You can also try notepad++ as your editor ;)

**Comment by maning** [comment]
@seav,

> I observed this in the nuvi. 

Are you using the beta/dev version?  I have no issues with the nuvi same as your model.

> But now that I looked at the code online at github, I saw "?" 

Fixed now.  @ralleon, can you merge the changes I made in your repo?

**Comment by seav** [comment]
On Sat, Jun 25, 2011 at 11:00 AM, maning
reply@reply.github.com
wrote:

> @seav,
> 
> > I observed this in the nuvi.
> > are you using the beta/dev version?  I have no issues with the nuvi same as your model.

I haven't actually loaded anything to the nuvi. It still contains the
beta map that rally presumably loaded onto the unit.

Looking at the Map Info page shows:

OSM_PHIL_Beta
[1] Luzon Island (63110001), Visayas-Mindanao (6321000...

**Comment by maning** [comment]
Fixed in commits f67e51acbd017d0bd25a and  df62f9aca77d3b7eeb9c
