### ISSUE TITLE
Adding date to `series-name` will not overwrite the installed maps in mac's roadtrip and basecamp

### ISSUE THREAD

**Issue by maning** [maning/osmphgps#27]
This line: 
https://github.com/maning/osmphgps/blob/master/build/build_script.sh#L40
which introduces a date in the series name, when installed via the gmapi file in roadtrip and basecamp will not overwrite the previous map.

**Comment by ralleon** [comment]
correct, that's the reason why i made beta in such a way that it puts only
the typ version.

...unless you can find a way to uninstall any osm map with a particular
unique identifier (eg. Family ID number), then install a new version over
it.

**Comment by maning** [comment]
Does this affect the mapsource installer?

Adding the date on the map can help us later on to debug reported problems instead of just the word "latest".

On Mon, Jun 27, 2011 at 11:04 AM, ralleon
reply@reply.github.com
wrote:

> correct, that's the reason why i made beta in such a way that it puts only
> the typ version.
> 
> ...unless you can find a way to uninstall any osm map with a particular
> unique identifier (eg. Family ID number), then install a new version over
> it.
> 
> On Mon, Jun 27, 2011 at 9:00 AM, maning <
> reply@reply.github.com>wrote:
> 
> > This line:
> > https://github.com/maning/osmphgps/blob/master/build/build_script.sh#L40
> > which introduces a date in the series name, when installed via the gmapi
> > file in roadtrip and basecamp will not overwrite the previous map.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/maning/osmphgps/issues/27
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/maning/osmphgps/issues/27#issuecomment-1445015

## 

cheers,

## maning

"Freedom is still the most radical idea of all" -N.Branden
wiki: http://esambale.wikispaces.com/

## blog: http://epsg4253.wordpress.com/

**Comment by ralleon** [comment]
make the uninstaller remove the specific product_name & product_version
(which will be different every time).

what if you just execute "delete all" folder and subfolders of a particular
family ID prior to installation of a new version. - so that you have clean
install everytime (as well as the windows menu)

**Comment by maning** [comment]
The mapsource installer does this already by overwriting the installed
osm-ph garmin map folder in the `Program files` directory. This
becomes an issue wih gmapi maps for mac.

On 6/27/11, ralleon
reply@reply.github.com
wrote:

> make the uninstaller remove the specific product_name & product_version
> (which will be different every time).
> 
> what if you just execute "delete all" folder and subfolders of a particular
> family ID prior to installation of a new version. - so that you have clean
> install everytime (as well as the windows menu)
> 
> On Mon, Jun 27, 2011 at 11:13 AM, maning <
> reply@reply.github.com>wrote:
> 
> > Does this affect the mapsource installer?
> > 
> > Adding the date on the map can help us later on to debug reported problems
> >  instead of just the word "latest"
> > 
> > On Mon, Jun 27, 2011 at 11:04 AM, ralleon
> > reply@reply.github.com
> > wrote:
> > 
> > > correct, that's the reason why i made beta in such a way that it puts
> > > only
> > > the typ version.
> > > 
> > > ...unless you can find a way to uninstall any osm map with a particular
> > > unique identifier (eg. Family ID number), then install a new version
> > > over
> > > it.
> > > 
> > > On Mon, Jun 27, 2011 at 9:00 AM, maning <
> > > reply@reply.github.com>wrote:
> > > 
> > > > This line:
> > > > 
> > > > https://github.com/maning/osmphgps/blob/master/build/build_script.sh#L40
> > > > which introduces a date in the series name, when installed via the
> > > > gmapi
> > > > file in roadtrip and basecamp will not overwrite the previous map.
> > > > 
> > > > ## 
> > > > 
> > > > Reply to this email directly or view it on GitHub:
> > > > https://github.com/maning/osmphgps/issues/27
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/maning/osmphgps/issues/27#issuecomment-1445015
> > 
> > ## 
> > 
> > cheers,
> > 
> > ## maning
> > 
> > "Freedom is still the most radical idea of all" -N.Branden
> > wiki: http://esambale.wikispaces.com/
> > 
> > ## blog: http://epsg4253.wordpress.com/
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/maning/osmphgps/issues/27#issuecomment-1445039
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/maning/osmphgps/issues/27#issuecomment-1445098

## 

cheers,

## maning

"Freedom is still the most radical idea of all" -N.Branden
wiki: http://esambale.wikispaces.com/

## blog: http://epsg4253.wordpress.com/

**Comment by maning** [comment]
This only affects installed maps in Mac.  A workaround is to manually delete the maps at `~/Library/Application Support/Garmin/Maps`
