### ISSUE TITLE
include addr data as POI

### ISSUE THREAD

**Issue by maning** [maning/osmphgps#32]
create a minimal searchable POI for address data.
@ralleon, what hex would you reccomend?

**Comment by ralleon** [comment]
let's sacrifice any unused hexcode of geographic land feature. you can try
the following. Just assign an invisible or a low profile "dot" on TYP
660b gap
660c isthmus
660e lava
660f pillar

they are currently not searchable in mapsource v6.13.7
but i expect them to be searchable in the latest version of mapsource,
basecamp, and when loaded in garmin receivers

I cannot experiment or compile on mkgmap right now, as I'm currently
experiencing unexplained (clueless)
Error in style: Error.... Stack size is 2

**Comment by maning** [comment]
Too much clutter, should be removed in the public map.

**Comment by ralleon** [comment]
must advise the user that the details is optimized at "high", not higher or
highest
