### ISSUE TITLE
Residential building POIs clutter up the map

### ISSUE THREAD

**Issue by seav** [maning/osmphgps#37]
![screenshot](http://forge.codedgraphic.com/osm/cluttered-residential-buildings.gif)

Maybe we should not create a POI for buildings that have no names?

**Comment by ralleon** [comment]
I hate seeing that default blue building POI which shows up when zoomed in
Nuvi

was this on a Nuvi 255W?
hmmm... i thought I address this already (replaced it with a gray round dot)
or is it for bigger commercial buildings only?

**Comment by seav** [comment]
Ah wait. Maybe this is already fixed in the beta. This screenshot is from the regular map. :-p

**Comment by maning** [comment]
Closing since this was solved in the beta (soon to be released).
