### ISSUE TITLE
Two Maps in one GPS

### ISSUE THREAD

**Issue by Manoi** [maning/osmphgps#42]
Hi Guys,

I am presently using a Roadguide on my Garmin Nuvi 2360. Recently, I tried to load OSM on my unit and successfully installed it but when I checked on my Maps, my Roadguide map was deleted. 

Is there a way for me to load OSM without deleting the Roadguide Map? I like to have both of the maps so that I can switch from one map to the other every time I need something that is not present on the other.

Thanks a lot.

Manoi

**Comment by maning** [comment]
You can save one map in your internal SD memory and the other to your removable SD card.
