### ISSUE TITLE
Tags for rice fields and other farms

### ISSUE THREAD

**Issue by ianlopez1115** [maning/osmphgps#43]
Since some users map rice fields with the landuse=meadow and name=Rice Field tag, may I suggest that there should be a customized label/style for a similar tag (landuse=farm; crops=rice should have the name Rice Field when rendered in the Default style). This _should_ help minimize the instance of "Tagging for the Renderer"

**Comment by maning** [comment]
@ianlopez1115, are you suggesting a separate color and a name Rice Field for `landuse=farm & crops-rice`?

**Comment by ianlopez1115** [comment]
Just the name "Rice field" for landuse=farm and crops=rice

**Comment by maning** [comment]
My only fear is that we get too much label clutter that is not very useful for anything.  See sample below:
!["landuse=farm, name=Rice field"](http://farm7.static.flickr.com/6224/6264898979_9205755c50.jpg)

**Comment by ianlopez1115** [comment]
Okay. That was a bad idea.

**Comment by maning** [comment]
@ianlopez1115, not really, maybe a different rendering/color style?

**Comment by ianlopez1115** [comment]
@maning why not? I prefer a more golden brown color style for the rice field

**Comment by maning** [comment]
OK.  It's on the list then.

**Comment by maning** [comment]
Too old issue. Closing.
